# Site Settings
title: "Aidan Sirbu"
title_separator: "–"
url: "https://asirbu77.github.io"
locale: "en-IN"
timezone: "America/Montreal"

# Site Author
author:
  name: "Aidan Sirbu"
  tagline: "MSc Student at Mila & McGill University"
  avatar: "profile.png"
  og_image: "icon.jpg"
  bio-short: >-
    My research interests lie at the intersection of deep learning and computational neuroscience. My focus is on building embodied agents for investigating theories of motor control and sensorimotor learning.
  bio: >-
    <p>I am a MSc student supervised by <a href='https://mila.quebec/en/directory/blake-richards' target='_blank' rel='noopener noreferrer'> Dr. Blake A. Richards</a> at Mila – Quebec AI Institute and McGill University. My research interests lie at the intersection of deep learning and computational neuroscience. I am particularly interested in building embodied agents to investigate theories of motor control and sensorimotor learning.</p>

    <p>My current projects focus on developing a framework for simulating and training embodied neuro-agents in virtual physics environments, as well as exploring the use of generative models for understanding and predicting motor behaviors.</p>
    
    <p>Before I joined Mila, I completed my BSc in Medical Physics at Western University where I worked on projects related to hyperpolarized MRI.</p>

    <p>In my free time, I am an avid rock climber, hiker, and motorcycle rider.</p>

    <p>Don't hesitate to reach out if you are interested in collaborating, discussing research, or even just chatting!</p>
  location: "Montréal, Canada"
  email: "aidan.sirbu@mila.quebec"
  social:
    github: "https://github.com/asirbu77"
    google-scholar: "https://scholar.google.com/citations?user=VQ1HT0oAAAAJ&hl=en"
    orcid: "https://orcid.org/0000-0002-0154-3563"
    linkedin: "https://www.linkedin.com/in/aidansirbu/"
    # x-twitter: 
    bluesky: "https://bsky.app/profile/sirbu.bsky.social"

# Analytics
analytics:
  activate: true
  measurement_id: "G-4NJNK1CES8"

# Mapbox
# mapbox:
#   activate: true
#   token: "pk.eyJ1IjoibmFuZGFoa3Jpc2huYSIsImEiOiJjbHJ0bDRoNzYwNXdlMm50ZWNtNzBseHQ1In0._L-eeGKeLcyrSDa8cuF1nA"

# Reading Files
include:
  - _pages
  - assets
exclude:
  - .jekyll-cache/
  - .sass-cache/
  - .ruby-version
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - LICENSE-MIT.md
  - LICENSE-CC.md
  - NOTICE.md
  - README.md

# Blog
# pagination:
#   enabled: true
#   sort_reverse: true
#   per_page: 5
#   title: "Blog"
#   permalink: "/page:num/"

# Sass
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-tidy
