volunteering:
  - "Organiser of the <a href='https://cosyne.org' target='_blank' rel='noopener noreferrer'>COSYNE</a> 2025 Workshop \"Foundation models of the brain: data, theory and models\"."
  - Member of the Student Recruitment Committee at Mila, 2025–present.
  - Technical Lead and Member of the <a href='https://unique-students.github.io' target='_blank' rel='noopener noreferrer'>UNIQUE Student Affairs Committee</a>, 2022–24.
  - Organiser of the <a href='https://unique-students.github.io/pastevents' target='_blank' rel='noopener noreferrer'>UNIQUE Student Symposium</a>, 2022–24.
  - Organiser of the <a href='https://sites.google.com/mila.quebec/neural-ai-mtl' target='_blank' rel='noopener noreferrer'>Neural-AI Reading Group</a> at Mila, 2022–present.

reviewing:
  - International Conference on Machine Learning (<a href='https://icml.cc' target='_blank' rel='noopener noreferrer'>ICML</a>), 2025
  - Artificial Intelligence and Statistics (<a href='https://aistats.org' target='_blank' rel='noopener noreferrer'>AISTATS</a>), 2025
  - Internation Conference on Learning Representations (<a href='https://iclr.cc' target='_blank' rel='noopener noreferrer'>ICLR</a>), 2025
  - Neural Information Processing Systems (<a href='https://neurips.cc' target='_blank' rel='noopener noreferrer'>NeurIPS</a>), 2024 and 2025
  - <a href='https://neuroai-workshop.github.io' target='_blank' rel='noopener noreferrer'>NeuroAI Workshop</a> at NeurIPS, 2024
  - Representational Alignment (<a href='https://representational-alignment.github.io' target='_blank' rel='noopener noreferrer'>Re-Align</a>) Workshop at ICLR, 2024 and 2025
  - Unifying Representations in Neural Models (<a href='https://unireps.org' target='_blank' rel='noopener noreferrer'>UniReps</a>) Workshop at NeurIPS, 2023 and 2024
  - Montréal AI Symposium (<a href='https://montrealaisymposium.wordpress.com' target='_blank' rel='noopener noreferrer'>MAIS</a>), 2022 and 2024
